#Socket Validate Mail Default
socket.mail.ip=localhost
socket.mail.port=15557
socket.mail.token.auth=4c263c17ce4874dd99c56f673fb856e8dd53c693da4da8a58fd34e4197b234f6
#Socket Validate gMail
socket.gmail.port=15557 
#Socket Validate Yahoo
socket.ymail.port=15557 
#Socket Validate hotmail
socket.hmail.port=15557 

#logging
logging.level.org.springframework.data=debug
logging.level.cl.integrador.bsale=DEBUG
logging.file.name=/var/log/integrador/checkEmail.log
logging.pattern.file=%d [%24F:%L] - %m%n

#spring
spring.profiles.active=Production,Dev
spring.jmx.default-domain=checkMail-v2

# HikariCP settings
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=HikariPoolBooks

# JPA settings
spring.datasource.url=jdbc:postgresql://144.22.51.190:5432/SGCA?currentSchema=public&sslmode=disable&search_path=public
spring.datasource.username=system
spring.datasource.password=Julio..2024
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=cl.integrador.bsale.woowup.util.UpperTableStrategy
spring.jpa.properties.hibernate.format_sql=true
hibernate.globally_quoted_identifiers=true


